import type { DebateResult } from "../orchestrator/index.js";
import type { ConsensusSection } from "../orchestrator/convergence.js";

export function exportToMarkdown(result: DebateResult): string {
  const lines: string[] = [];
  const agentNames = Object.keys(result.agentResponses);

  lines.push("# Technical Specification");
  lines.push("");
  lines.push(`> Generated by Twofer — ${result.rounds.length} round(s) of debate with ${agentNames.join(", ")}`);
  lines.push(`> Convergence: ${result.convergenceState.reason ?? "N/A"}`);
  lines.push("");

  const agreed = result.consensus.filter((s) => s.agreed);
  const disputed = result.consensus.filter((s) => !s.agreed);

  if (agreed.length > 0) {
    lines.push("## Agreed Sections");
    lines.push("");
    for (const section of agreed) {
      lines.push(`### ${section.title}`);
      lines.push("");
      lines.push(section.finalContent || Object.values(section.agentContents)[0] || "");
      lines.push("");
    }
  }

  if (disputed.length > 0) {
    lines.push("## Disputed Sections");
    lines.push("");
    for (const section of disputed) {
      lines.push(`### ${section.title}`);
      lines.push("");
      for (const [agentName, content] of Object.entries(section.agentContents)) {
        lines.push(`#### ${agentName}'s Position`);
        lines.push("");
        lines.push(content);
        lines.push("");
      }
    }
  }

  // Round history
  lines.push("---");
  lines.push("");
  lines.push("## Debate History");
  lines.push("");
  for (const round of result.rounds) {
    lines.push(`### Round ${round.round}`);
    lines.push("");
    for (const [name, resp] of Object.entries(round.responses)) {
      lines.push(`- **${name} verdict**: ${resp.overall_verdict}`);
      lines.push(`- **${name} summary**: ${resp.summary}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function consensusToSpec(sections: ConsensusSection[]): string {
  return sections
    .filter((s) => s.agreed)
    .map((s) => `## ${s.title}\n\n${s.finalContent || Object.values(s.agentContents)[0] || ""}`)
    .join("\n\n");
}
